### ISSUE TITLE
Segmentation fault when using aligner from multiple threads

### ISSUE THREAD

**Issue by felbecker** [althonos/pyfamsa#1]
Hi,

Thank you for putting work into this useful package.

I'm getting a segmentation fault (no error message) with the following piece of code:

```
import multiprocessing.pool
from pyfamsa import Aligner as FamsaAligner, Sequence as FamsaSequence

seqs = [ [('1hre\n', 'CTENVPMKVQNQEKAEELYQK'), 
            ('1dan2\n', 'DGVSCTPTVEYPCGKIPILE'), 
            ('1rfnb\n', 'NQKSCEPAVPFPCGRVSVSQTSK'), 
            ('1hcgb\n', 'NGKACIPTGPYPCGKQTLER')], 
             [('D2HBN8_AILME/319-369\n', 'SPEEQYGRLAQLPSSFSHPE'), 
            ('A8K118_HUMAN/343-393\n', 'SSEKQYGRITGLPSSFSYHE'), 
            ('B7Z826_HUMAN/274-324\n', 'SSEKQYGRITGLPSSFSYHE'), 
            ('CRUM1_HUMAN/343-393\n', 'SSEKQYGRITGLPSSFSYHE'),
            ('B7Z5T2_HUMAN/343-393\n', 'SSEKQYGRITGLPSSFSYHE'), 
            ('Q59H36_HUMAN/368-418\n', 'SSEKQYGRITGLPSSFSYHE'), 
            ('Q95LN0_MACFA/323-373\n', 'SSEKQYGHITGLPSTFSYHE'), 
            ('B7Z5T1_HUMAN/42-92\n', 'SSEKQYGRITGLPSSSSYHE'), 
            ('C3ZUH9_BRAFL/3770-3822\n', 'LQVTSSRNILESDPVIFVSVDT'), 
            ('Q1L927_DANRE/354-404\n', 'SWKTLYGTEPLFTARYNPRL'), 
            ('C4QSG7_SCHMA/5-55\n', 'GGISNSSTIAITTTTFNNNG')] ]
enc_seqs = [[FamsaSequence(sid.encode(), seq.encode()) for sid,seq in s] for s in seqs]
aligner = FamsaAligner()
with multiprocessing.pool.ThreadPool() as pool:
    alignments = pool.map(aligner.align, enc_seqs)
```

It works fine when aligning sequentially rather than parallel.

Since the famsa aligner is already highly parallel and makes use of all CPU cores, I wonder if parallelizing over the families/datasets is even important as a feature? I noticed no benefit in performance so far.

**Comment by althonos** [comment]
Hi @felbecker ,

Even though this is probably not needed to support parallel calls to the `Aligner.align` method, since as you pointed the `Aligner` uses multithreading internally, it's still worrying that there would be segfaults if the method was called across several threads. I did try disabling the use of `memory-monotonic` to allocate the internal `CSequence` buffer, and there I didn't see segfaults anymore. I'd have to dig in more as to why this happens, but for now I can just make a patch to disable it.

**Comment by althonos** [comment]
Sorry I realized I never uploaded a patch, it's now live in `v0.3.1`.
